# Generated by Django 3.0.9 on 2020-09-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruserapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
