# Generated by Django 3.0.9 on 2020-09-07 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruserapp', '0004_auto_20200904_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, default=0, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
