# Generated by Django 3.0.9 on 2020-09-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
