# Generated by Django 3.0.9 on 2020-09-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0003_tweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
    ]
