# Generated by Django 3.0.9 on 2020-09-04 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0003_tweet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('at_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('the_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetapp.Tweet')),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
