# Generated by Django 3.0.9 on 2020-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0003_auto_20200907_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_flag',
            field=models.BooleanField(default=False),
        ),
    ]
